/**
 * Admin routes for managing BoostiSwap artists
 * These are the 20 static artists displayed in the BoostiSwap marketplace
 */

import { Router, Request, Response } from "express";
import { db } from "../db";
import { users } from "../db/schema";
import { eq, isNull, desc, ilike, or } from "drizzle-orm";

const router = Router();

/**
 * GET /api/admin/boostiswap-artists
 * Get all BoostiSwap artists (those without generatedBy - static marketplace artists)
 */
router.get("/", async (req: Request, res: Response) => {
  try {
    const { search } = req.query;
    
    // Get artists that are NOT AI-generated by a user (generatedBy is null)
    // These are the static BoostiSwap marketplace artists
    let query = db.select({
      id: users.id,
      artistName: users.artistName,
      slug: users.slug,
      biography: users.biography,
      profileImage: users.profileImage,
      coverImage: users.coverImage,
      genres: users.genres,
      country: users.country,
      location: users.location,
      instagramHandle: users.instagramHandle,
      twitterHandle: users.twitterHandle,
      youtubeHandle: users.youtubeChannel,
      spotifyUrl: users.spotifyUrl,
      isAIGenerated: users.isAIGenerated,
      createdAt: users.createdAt,
    })
    .from(users)
    .where(isNull(users.generatedBy));
    
    // Apply search filter if provided
    if (search && typeof search === 'string') {
      query = query.where(
        or(
          ilike(users.artistName, `%${search}%`),
          ilike(users.slug, `%${search}%`)
        )
      );
    }
    
    const artists = await query.orderBy(desc(users.createdAt));
    
    console.log(`📊 [ADMIN] Found ${artists.length} BoostiSwap artists`);
    
    res.json({ 
      success: true, 
      artists,
      count: artists.length 
    });
  } catch (error) {
    console.error("❌ [ADMIN] Error fetching BoostiSwap artists:", error);
    res.status(500).json({ 
      success: false, 
      error: "Error fetching BoostiSwap artists" 
    });
  }
});

/**
 * GET /api/admin/boostiswap-artists/:id
 * Get a single BoostiSwap artist by ID
 */
router.get("/:id", async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    
    const artist = await db.select()
      .from(users)
      .where(eq(users.id, parseInt(id)))
      .limit(1);
    
    if (!artist.length) {
      return res.status(404).json({ 
        success: false, 
        error: "Artist not found" 
      });
    }
    
    res.json({ success: true, artist: artist[0] });
  } catch (error) {
    console.error("❌ [ADMIN] Error fetching artist:", error);
    res.status(500).json({ 
      success: false, 
      error: "Error fetching artist" 
    });
  }
});

/**
 * PATCH /api/admin/boostiswap-artists/:id
 * Update a BoostiSwap artist
 */
router.patch("/:id", async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { 
      artistName, 
      slug, 
      biography, 
      profileImage, 
      coverImage, 
      genres, 
      country, 
      location,
      instagramHandle,
      twitterHandle,
      youtubeHandle,
      spotifyUrl
    } = req.body;
    
    const updateData: any = { updatedAt: new Date() };
    
    if (artistName !== undefined) updateData.artistName = artistName;
    if (slug !== undefined) updateData.slug = slug;
    if (biography !== undefined) updateData.biography = biography;
    if (profileImage !== undefined) updateData.profileImage = profileImage;
    if (coverImage !== undefined) updateData.coverImage = coverImage;
    if (genres !== undefined) updateData.genres = genres;
    if (country !== undefined) updateData.country = country;
    if (location !== undefined) updateData.location = location;
    if (instagramHandle !== undefined) updateData.instagramHandle = instagramHandle;
    if (twitterHandle !== undefined) updateData.twitterHandle = twitterHandle;
    if (youtubeHandle !== undefined) updateData.youtubeChannel = youtubeHandle;
    if (spotifyUrl !== undefined) updateData.spotifyUrl = spotifyUrl;
    
    const result = await db
      .update(users)
      .set(updateData)
      .where(eq(users.id, parseInt(id)))
      .returning();
    
    if (!result.length) {
      return res.status(404).json({ 
        success: false, 
        error: "Artist not found" 
      });
    }
    
    console.log(`✅ [ADMIN] Updated BoostiSwap artist: ${result[0].artistName} (ID: ${id})`);
    
    res.json({ success: true, artist: result[0] });
  } catch (error) {
    console.error("❌ [ADMIN] Error updating artist:", error);
    res.status(500).json({ 
      success: false, 
      error: "Error updating artist" 
    });
  }
});

/**
 * DELETE /api/admin/boostiswap-artists/:id
 * Delete a BoostiSwap artist
 */
router.delete("/:id", async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    
    const result = await db
      .delete(users)
      .where(eq(users.id, parseInt(id)))
      .returning();
    
    if (!result.length) {
      return res.status(404).json({ 
        success: false, 
        error: "Artist not found" 
      });
    }
    
    console.log(`🗑️ [ADMIN] Deleted BoostiSwap artist: ${result[0].artistName} (ID: ${id})`);
    
    res.json({ 
      success: true, 
      message: "Artist deleted successfully" 
    });
  } catch (error) {
    console.error("❌ [ADMIN] Error deleting artist:", error);
    res.status(500).json({ 
      success: false, 
      error: "Error deleting artist" 
    });
  }
});

export default router;
