import { fal } from "@fal-ai/client";
import axios from 'axios';

// Configure fal client
if (!import.meta.env.VITE_FAL_API_KEY) {
  console.error("VITE_FAL_API_KEY is not configured");
}

fal.config({
  credentials: import.meta.env.VITE_FAL_API_KEY
});

interface GenerateImageParams {
  prompt: string;
  negativePrompt?: string;
  imageSize?: string;
}

interface GenerateAudioParams {
  prompt: string;
  duration_seconds?: number;
}

export async function generateImageWithFal(params: GenerateImageParams) {
  console.log("Starting image generation with params:", {
    ...params,
    prompt: params.prompt.substring(0, 50) + "..." // Log truncated prompt for privacy
  });

  // Enhance prompt quality with more specific details
  const enhancedPrompt = enhancePrompt(params.prompt);
  
  try {
    const result = await fal.subscribe("fal-ai/flux-pro", {
      input: {
        prompt: enhancedPrompt,
        negative_prompt: params.negativePrompt || "low quality, bad anatomy, blurry, pixelated, watermarks, text, deformed, unrealistic",
        image_size: params.imageSize || "landscape_16_9",
        seed: Math.floor(Math.random() * 1000000), // Random seed for variety
        num_images: 1, // Generate a single high-quality image
        scheduler: "DPM++ 2M Karras", // Better quality scheduler
        guidance_scale: 7.5, // Standard guidance scale for balanced results
      },
      pollInterval: 5000, // Poll every 5 seconds
      logs: true,
      onQueueUpdate: (update) => {
        console.log("Generation status:", update.status);
        if (update.status === "IN_PROGRESS") {
          update.logs.map((log) => log.message).forEach(console.log);
        }
      },
    });

    console.log("Generation completed, result:", {
      requestId: result.requestId,
      hasImages: result.data?.images?.length > 0,
      imageSize: params.imageSize
    });

    // Validate and handle the result
    if (!result.data?.images || result.data.images.length === 0) {
      throw new Error("No images were generated by fal-ai");
    }

    return result;
  } catch (error) {
    console.error("Error generating image with Fal.ai:", error);
    throw error;
  }
}

// Helper function to enhance prompts for better image quality
function enhancePrompt(originalPrompt: string): string {
  // Check if prompt already has quality-related terms
  const hasQualityTerms = /high quality|high-quality|detailed|4k|photorealistic|professional/.test(originalPrompt.toLowerCase());
  
  if (!hasQualityTerms) {
    return `${originalPrompt}, high quality, professional, detailed`;
  }
  
  return originalPrompt;
}

/**
 * Generates audio using Fal.ai's stable audio model
 * @param params Parameters for audio generation
 * @returns Generated audio result
 */
export async function generateAudioWithFal(params: GenerateAudioParams) {
  console.log("Starting audio generation with params:", {
    ...params,
    prompt: params.prompt.substring(0, 50) + "..." // Log truncated prompt for privacy
  });

  try {
    // Type assertion to allow custom parameters for the stable-audio model
    // The fal.ai SDK types may not be up-to-date with the latest model parameters
    const result = await fal.subscribe("fal-ai/stable-audio", {
      input: {
        prompt: params.prompt,
        // Using type assertion to handle the duration_seconds parameter
        ...(params.duration_seconds ? { duration_seconds: params.duration_seconds } : {})
      } as any, // Type assertion to bypass type checking for model-specific parameters
      pollInterval: 5000, // Poll every 5 seconds
      logs: true,
      onQueueUpdate: (update) => {
        console.log("Audio generation status:", update.status);
        if (update.status === "IN_PROGRESS") {
          update.logs.map((log) => log.message).forEach(console.log);
        }
      },
    });

    // Extract audio URL from the response data (with type safety)
    const audioUrl = result.data && 'audio_url' in result.data ? 
      (result.data as any).audio_url : undefined;

    console.log("Audio generation completed, result:", {
      requestId: result.requestId,
      hasAudio: !!audioUrl
    });

    return result;
  } catch (error) {
    console.error("Error generating audio with Fal.ai:", error);
    throw error;
  }
}

// Test function to verify fal.ai integration with diagnostic information
export async function testFalIntegration() {
  console.log("Testing Fal.ai integration...");
  
  // Log environment variables (redacted for security)
  console.log("Environment check:", {
    hasFalApiKey: !!import.meta.env.VITE_FAL_API_KEY,
    falApiKeyLength: import.meta.env.VITE_FAL_API_KEY ? 
      `${import.meta.env.VITE_FAL_API_KEY.substring(0, 3)}...${import.meta.env.VITE_FAL_API_KEY.substring(import.meta.env.VITE_FAL_API_KEY.length - 3)}` : 
      'not available'
  });
  
  try {
    // Test with a specific educational prompt for better context 
    const testResult = await generateImageWithFal({
      prompt: "A professional music education course thumbnail showing a production studio for beginners, modern clean design",
      negativePrompt: "deformed, unrealistic, cartoon, anime, illustration, low quality, blurry, text, watermark, signature",
      imageSize: "square_1_1" // Test with square format used for course thumbnails
    });

    console.log("Fal.ai test successful, diagnostic info:", {
      requestId: testResult.requestId,
      hasImages: !!testResult.data?.images,
      imageCount: testResult.data?.images?.length || 0,
      imageFormat: typeof testResult.data?.images?.[0] === 'object' ? 'object with url' : 'direct string URL'
    });
    
    // Test result structure validation
    if (testResult.data?.images && testResult.data.images.length > 0) {
      let imageUrl;
      const firstImage = testResult.data.images[0];
      
      if (typeof firstImage === 'object' && firstImage.url) {
        imageUrl = firstImage.url;
      } else if (typeof firstImage === 'string') {
        imageUrl = firstImage;
      }
      
      console.log("Test image URL format:", {
        type: typeof imageUrl,
        urlStart: imageUrl ? imageUrl.substring(0, 30) + '...' : 'not available'
      });
    }
    
    return testResult;
  } catch (error) {
    console.error("Fal.ai test failed with error:", error);
    
    // Add diagnostic information
    if (error instanceof Error) {
      console.error("Error details:", {
        name: error.name,
        message: error.message,
        stack: error.stack?.substring(0, 200) + '...'
      });
    }
    
    throw error;
  }
}