/**
 * Seed data for 20 tokenized songs from artist profiles
 * Run this to populate initial data for BoostiSwap marketplace
 */
import { db } from './db';
import { tokenizedSongs } from './db/schema';
import { eq } from 'drizzle-orm';

// Use direct URLs instead of client-side function
const BOOSTIFY_CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000';

const artistImageMap: Record<number, string> = {
  1: "/artist-images/luna_echo_-_female_pop_singer.png",
  2: "/artist-images/urban_flow_-_hip-hop_artist.png",
  3: "/artist-images/electric_dreams_-_electronic_artist.png",
  4: "/artist-images/soul_harmony_-_r&b_artist.png",
  5: "/artist-images/maya_rivers_-_indie_folk.png",
  6: "/artist-images/jah_vibes_-_reggae_artist.png",
  7: "/artist-images/david_chen_-_classical_pianist.png",
  8: "/artist-images/sophia_kim_-_k-pop_star.png",
  9: "/artist-images/marcus_stone_-_jazz_saxophonist.png",
  10: "/artist-images/isabella_santos_-_reggaeton.png",
  11: "/artist-images/luke_bradley_-_country_artist.png",
  12: "/artist-images/aria_nova_-_ambient_electronic.png",
  13: "/artist-images/alex_thunder_-_trap_producer.png",
  14: "/artist-images/victoria_cross_-_opera_singer.png",
  15: "/artist-images/prince_diesel_-_funk_artist.png",
  16: "/artist-images/ryan_phoenix_-_indie_rock.png",
  17: "/artist-images/pablo_fuego_-_latin_artist.png",
  18: "/artist-images/emma_white_-_pop_princess.png",
  19: "/artist-images/chris_void_-_dubstep_producer.png",
  20: "/artist-images/james_grant_-_soul_singer.png",
};

function getArtistImage(artistId: number): string {
  return artistImageMap[artistId] || "";
}

export const TOKENIZED_SONGS_SEED = [
  {
    artistId: 1,
    songName: "Moonlight Dreams",
    songUrl: null,
    tokenId: 1,
    tokenSymbol: "LUNA",
    totalSupply: 10000,
    availableSupply: 3500,
    pricePerTokenUsd: "2.45",
    pricePerTokenEth: "0.005",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxLunaEcho001",
    imageUrl: getArtistImage(1),
    description: "A haunting synthwave track with ethereal vocals",
    benefits: ["Royalty rights", "VIP access", "Exclusive content"],
    isActive: true
  },
  {
    artistId: 2,
    songName: "Urban Rhythm",
    songUrl: null,
    tokenId: 2,
    tokenSymbol: "URBAN",
    totalSupply: 15000,
    availableSupply: 5200,
    pricePerTokenUsd: "3.15",
    pricePerTokenEth: "0.006",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxUrbanFlow001",
    imageUrl: getArtistImage(2),
    description: "High-energy hip-hop with infectious beats",
    benefits: ["Royalty rights", "NFT collectible", "Discord access"],
    isActive: true
  },
  {
    artistId: 3,
    songName: "Electric Pulse",
    songUrl: null,
    tokenId: 3,
    tokenSymbol: "ELDREAM",
    totalSupply: 8000,
    availableSupply: 1200,
    pricePerTokenUsd: "4.22",
    pricePerTokenEth: "0.008",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxElectricDreams001",
    imageUrl: getArtistImage(3),
    description: "Electropop sensation breaking charts worldwide",
    benefits: ["Royalty rights", "Concert invitations", "Merchandise"],
    isActive: true
  },
  {
    artistId: 4,
    songName: "Soul Connection",
    songUrl: null,
    tokenId: 4,
    tokenSymbol: "SOUL",
    totalSupply: 12000,
    availableSupply: 4100,
    pricePerTokenUsd: "2.88",
    pricePerTokenEth: "0.005",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxSoulHarmony001",
    imageUrl: getArtistImage(4),
    description: "Deep R&B with timeless soul vibes",
    benefits: ["Royalty rights", "Exclusive demos", "Fan club access"],
    isActive: true
  },
  {
    artistId: 5,
    songName: "River Road",
    songUrl: null,
    tokenId: 5,
    tokenSymbol: "MAYA",
    totalSupply: 9000,
    availableSupply: 3200,
    pricePerTokenUsd: "1.99",
    pricePerTokenEth: "0.004",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxMayaRivers001",
    imageUrl: getArtistImage(5),
    description: "Indie folk masterpiece with acoustic instrumentation",
    benefits: ["Royalty rights", "Album preorder", "Meet & greet"],
    isActive: true
  },
  {
    artistId: 6,
    songName: "Reggae Sunset",
    songUrl: null,
    tokenId: 6,
    tokenSymbol: "JAH",
    totalSupply: 11000,
    availableSupply: 4100,
    pricePerTokenUsd: "2.15",
    pricePerTokenEth: "0.004",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxJahVibes001",
    imageUrl: getArtistImage(6),
    description: "Relaxing reggae vibes for the soul",
    benefits: ["Royalty rights", "Studio sessions", "Collaboration"],
    isActive: true
  },
  {
    artistId: 7,
    songName: "Classical Symphony",
    songUrl: null,
    tokenId: 7,
    tokenSymbol: "CHEN",
    totalSupply: 5000,
    availableSupply: 800,
    pricePerTokenUsd: "5.50",
    pricePerTokenEth: "0.010",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxDavidChen001",
    imageUrl: getArtistImage(7),
    description: "A virtuosic classical composition",
    benefits: ["Royalty rights", "Private concerts", "Sheet music"],
    isActive: true
  },
  {
    artistId: 8,
    songName: "K-Pop Dream",
    songUrl: null,
    tokenId: 8,
    tokenSymbol: "SOPHIA",
    totalSupply: 12000,
    availableSupply: 2500,
    pricePerTokenUsd: "3.80",
    pricePerTokenEth: "0.007",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxSophiaKim001",
    imageUrl: getArtistImage(8),
    description: "Chart-topping K-pop sensation",
    benefits: ["Royalty rights", "Tour passes", "Limited edition"],
    isActive: true
  },
  {
    artistId: 9,
    songName: "Jazz Nights",
    songUrl: null,
    tokenId: 9,
    tokenSymbol: "MARCUS",
    totalSupply: 7000,
    availableSupply: 1500,
    pricePerTokenUsd: "4.15",
    pricePerTokenEth: "0.008",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxMarcusStone001",
    imageUrl: getArtistImage(9),
    description: "Smooth jazz saxophone performance",
    benefits: ["Royalty rights", "Jazz club events", "Recording sessions"],
    isActive: true
  },
  {
    artistId: 10,
    songName: "Reggaeton Fire",
    songUrl: null,
    tokenId: 10,
    tokenSymbol: "BELLA",
    totalSupply: 13000,
    availableSupply: 3800,
    pricePerTokenUsd: "3.45",
    pricePerTokenEth: "0.006",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxIsabellaSantos001",
    imageUrl: getArtistImage(10),
    description: "Hot reggaeton track with infectious rhythm",
    benefits: ["Royalty rights", "Festival appearances", "Streaming boost"],
    isActive: true
  },
  {
    artistId: 11,
    songName: "Country Roads",
    songUrl: null,
    tokenId: 11,
    tokenSymbol: "LUKE",
    totalSupply: 10000,
    availableSupply: 3900,
    pricePerTokenUsd: "2.65",
    pricePerTokenEth: "0.005",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxLukeBradley001",
    imageUrl: getArtistImage(11),
    description: "Classic country ballad",
    benefits: ["Royalty rights", "Country tour", "Album credits"],
    isActive: true
  },
  {
    artistId: 12,
    songName: "Ambient Cosmos",
    songUrl: null,
    tokenId: 12,
    tokenSymbol: "ARIA",
    totalSupply: 8500,
    availableSupply: 4200,
    pricePerTokenUsd: "2.20",
    pricePerTokenEth: "0.004",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxAriaNova001",
    imageUrl: getArtistImage(12),
    description: "Ethereal ambient electronic soundscape",
    benefits: ["Royalty rights", "Meditation sessions", "Sound design"],
    isActive: true
  },
  {
    artistId: 13,
    songName: "Trap Beats",
    songUrl: null,
    tokenId: 13,
    tokenSymbol: "ALEX",
    totalSupply: 11000,
    availableSupply: 2800,
    pricePerTokenUsd: "3.55",
    pricePerTokenEth: "0.007",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxAlexThunder001",
    imageUrl: getArtistImage(13),
    description: "Heavy trap production masterpiece",
    benefits: ["Royalty rights", "Producer credits", "Beat packs"],
    isActive: true
  },
  {
    artistId: 14,
    songName: "Opera Aria",
    songUrl: null,
    tokenId: 14,
    tokenSymbol: "VICTORIA",
    totalSupply: 4000,
    availableSupply: 600,
    pricePerTokenUsd: "6.10",
    pricePerTokenEth: "0.012",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxVictoriaCross001",
    imageUrl: getArtistImage(14),
    description: "Classical opera performance",
    benefits: ["Royalty rights", "Opera house events", "Performance rights"],
    isActive: true
  },
  {
    artistId: 15,
    songName: "Funk Groove",
    songUrl: null,
    tokenId: 15,
    tokenSymbol: "DIESEL",
    totalSupply: 9500,
    availableSupply: 2200,
    pricePerTokenUsd: "3.90",
    pricePerTokenEth: "0.008",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxPrinceDiesel001",
    imageUrl: getArtistImage(15),
    description: "Funky rhythmic groove",
    benefits: ["Royalty rights", "Funk festivals", "Dancing events"],
    isActive: true
  },
  {
    artistId: 16,
    songName: "Rock Anthem",
    songUrl: null,
    tokenId: 16,
    tokenSymbol: "RYAN",
    totalSupply: 10500,
    availableSupply: 3600,
    pricePerTokenUsd: "3.25",
    pricePerTokenEth: "0.006",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxRyanPhoenix001",
    imageUrl: getArtistImage(16),
    description: "Indie rock anthem",
    benefits: ["Royalty rights", "Rock shows", "Band merchandise"],
    isActive: true
  },
  {
    artistId: 17,
    songName: "Latin Fire",
    songUrl: null,
    tokenId: 17,
    tokenSymbol: "PABLO",
    totalSupply: 12000,
    availableSupply: 4500,
    pricePerTokenUsd: "2.99",
    pricePerTokenEth: "0.006",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxPabloFuego001",
    imageUrl: getArtistImage(17),
    description: "Energetic Latin music",
    benefits: ["Royalty rights", "Latin festivals", "Dance classes"],
    isActive: true
  },
  {
    artistId: 18,
    songName: "Pop Perfection",
    songUrl: null,
    tokenId: 18,
    tokenSymbol: "EMMA",
    totalSupply: 13500,
    availableSupply: 3200,
    pricePerTokenUsd: "3.55",
    pricePerTokenEth: "0.007",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxEmmaWhite001",
    imageUrl: getArtistImage(18),
    description: "Catchy pop hit",
    benefits: ["Royalty rights", "Fan club", "Meet & greet"],
    isActive: true
  },
  {
    artistId: 19,
    songName: "Dubstep Drop",
    songUrl: null,
    tokenId: 19,
    tokenSymbol: "VOID",
    totalSupply: 9000,
    availableSupply: 1800,
    pricePerTokenUsd: "4.05",
    pricePerTokenEth: "0.008",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxChrisVoid001",
    imageUrl: getArtistImage(19),
    description: "Massive dubstep bass drop",
    benefits: ["Royalty rights", "Rave events", "Remix packs"],
    isActive: true
  },
  {
    artistId: 20,
    songName: "Soul Serenade",
    songUrl: null,
    tokenId: 20,
    tokenSymbol: "JAMES",
    totalSupply: 11000,
    availableSupply: 3400,
    pricePerTokenUsd: "3.35",
    pricePerTokenEth: "0.006",
    royaltyPercentageArtist: 80,
    royaltyPercentagePlatform: 20,
    contractAddress: BOOSTIFY_CONTRACT_ADDRESS,
    metadataUri: "ipfs://QmXxJamesGrant001",
    imageUrl: getArtistImage(20),
    description: "Soulful R&B ballad",
    benefits: ["Royalty rights", "Soul nights", "Studio collab"],
    isActive: true
  }
];

export async function seedTokenizedSongs() {
  try {
    console.log("🌱 Iniciando seed de canciones tokenizadas...");
    
    for (const song of TOKENIZED_SONGS_SEED) {
      const existing = await db.select().from(tokenizedSongs)
        .where(eq(tokenizedSongs.tokenId, song.tokenId));
      
      if (existing.length === 0) {
        await db.insert(tokenizedSongs).values(song);
        console.log(`✅ Creada: ${song.songName} (Token ID: ${song.tokenId})`);
      } else {
        console.log(`⏭️  Ya existe: ${song.songName}`);
      }
    }
    
    console.log("✅ Seed completado!");
  } catch (error) {
    console.error("❌ Error en seed:", error);
  }
}
