import { db } from "../db";
import { socialUsers, posts, comments } from "../db/schema";
import { faker } from "@faker-js/faker";
import { eq } from "drizzle-orm";

// Function to generate random response using OpenRouter
async function generateOpenRouterResponse(prompt: string): Promise<string> {
  try {
    const openRouterApiKey = process.env.OPENROUTER_API_KEY;
    
    if (!openRouterApiKey) {
      console.log("OpenRouter API key not found, using fallback response");
      return `This is a fallback response to: ${prompt}. In a real scenario, this would be generated by AI.`;
    }
    
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${openRouterApiKey}`
      },
      body: JSON.stringify({
        model: "anthropic/claude-3-opus:beta",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 500
      })
    });
    
    if (!response.ok) {
      throw new Error(`OpenRouter API error: ${response.status}`);
    }
    
    const data = await response.json();
    return data.choices[0].message.content;
  } catch (error) {
    console.error("Error generating OpenRouter response:", error);
    return `Error generating AI response. This is a fallback message for: ${prompt}`;
  }
}

async function seedSocialNetwork() {
  console.log("🌱 Starting social network seed process...");
  
  try {
    // Clear existing data
    console.log("Clearing existing data...");
    await db.delete(comments);
    await db.delete(posts);
    await db.delete(socialUsers);
    
    // Create bot personalities
    const personalities = [
      { name: "Helpful Assistant", personality: "friendly, informative, and always eager to help" },
      { name: "Music Expert", personality: "knowledgeable about music theory, production techniques, and industry trends" },
      { name: "Marketing Guru", personality: "focused on promotion strategies, social media growth, and audience engagement" },
      { name: "Tech Innovator", personality: "enthusiastic about new technologies, AI, and innovative tools for musicians" },
      { name: "Industry Veteran", personality: "experienced in the music business with practical advice and industry connections" }
    ];
    
    const languages = ["es", "en"];
    const interests = [
      ["música", "producción musical", "marketing digital", "redes sociales"],
      ["songwriting", "audio engineering", "artist development", "industry networking"],
      ["composición", "tecnología musical", "promoción artística", "educación musical"],
      ["performance", "mixing", "branding", "distribution"],
      ["instrumentos musicales", "colaboraciones", "monetización", "tendencias musicales"]
    ];
    
    // Create users (15 regular + 5 bots)
    console.log("Creating users...");
    const userIds: string[] = [];
    
    // Create regular users (15)
    for (let i = 0; i < 15; i++) {
      const language = languages[Math.floor(Math.random() * languages.length)];
      const userInterests = interests[Math.floor(Math.random() * interests.length)];
      
      const newUser: any = {
        username: faker.internet.userName().toLowerCase().replace(/[^a-z0-9]/g, ''),
        displayName: faker.person.fullName(),
        avatar: faker.image.avatar(),
        bio: faker.person.bio(),
        language,
        isBot: false,
        personality: null,
        interests: userInterests
      };
      
      const [user] = await db.insert(socialUsers).values(newUser).returning({ id: socialUsers.id });
      userIds.push(user.id);
    }
    
    // Create AI bot users (5)
    for (let i = 0; i < 5; i++) {
      const botPersonality = personalities[i];
      const language = languages[Math.floor(Math.random() * languages.length)];
      const userInterests = interests[Math.floor(Math.random() * interests.length)];
      
      const newUser: any = {
        username: faker.internet.userName().toLowerCase().replace(/[^a-z0-9]/g, '') + "_bot",
        displayName: botPersonality.name,
        avatar: faker.image.avatar(),
        bio: `AI assistant specializing in ${botPersonality.personality}`,
        language,
        isBot: true,
        personality: botPersonality.personality,
        interests: userInterests
      };
      
      const [user] = await db.insert(socialUsers).values(newUser).returning({ id: socialUsers.id });
      userIds.push(user.id);
    }
    
    // Create posts
    console.log("Creating posts...");
    const postIds: string[] = [];
    const postContents = [
      "¿Alguien tiene consejos para promocionar música en Spotify?",
      "Just finished my new track! Can't wait to share it with you all.",
      "Estoy buscando colaboradores para mi próximo álbum. ¿Alguien interesado?",
      "What mixing software do you recommend for hip-hop production?",
      "Acabo de lanzar mi EP. ¡Espero que les guste!",
      "Looking for tips on getting more engagement on music videos",
      "¿Cuál es la mejor estrategia para crecer en redes sociales como artista?",
      "Sharing my journey from bedroom producer to signed artist",
      "¿Qué opinan de las nuevas plataformas de streaming?",
      "Anyone else finding TikTok great for music promotion?",
      "Estoy organizando un concierto virtual. ¿Quiénes se unen?",
      "Just got my first 10k streams! Thank you to everyone who supported me",
      "¿Qué equipo de grabación recomiendan para principiantes?",
      "Thoughts on AI music production tools? Helpful or harmful?",
      "Necesito consejos para negociar con sellos discográficos"
    ];
    
    for (let i = 0; i < postContents.length; i++) {
      const randomUserId = userIds[Math.floor(Math.random() * userIds.length)];
      const randomLikes = Math.floor(Math.random() * 50);
      const randomShares = Math.floor(Math.random() * 20);
      
      const newPost: any = {
        userId: randomUserId,
        content: postContents[i],
        mediaUrl: Math.random() > 0.7 ? faker.image.url() : null,
        likes: randomLikes,
        shares: randomShares
      };
      
      const [post] = await db.insert(posts).values(newPost).returning({ id: posts.id });
      postIds.push(post.id);
    }
    
    // Create comments and replies
    console.log("Creating comments and replies...");
    for (const postId of postIds) {
      // Get post details for context
      const [postDetails] = await db.select().from(posts).where(eq(posts.id, postId));
      const [postAuthor] = await db.select().from(socialUsers).where(eq(socialUsers.id, postDetails.userId));
      
      // Generate 2-5 main comments per post
      const commentCount = 2 + Math.floor(Math.random() * 4);
      const commentIds: string[] = [];
      
      for (let i = 0; i < commentCount; i++) {
        // Select a commenter (not the post author)
        let commenterId;
        do {
          commenterId = userIds[Math.floor(Math.random() * userIds.length)];
        } while (commenterId === postDetails.userId);
        
        const [commenter] = await db.select().from(socialUsers).where(eq(socialUsers.id, commenterId));
        
        // Generate comment content
        let commentContent;
        if (commenter.isBot) {
          // AI-generated response
          const userInterests = commenter.interests || ['music'];
          const prompt = `You are a social media user with the following personality: ${commenter.personality}. 
            You're interested in: ${userInterests.join(', ')}.
            Please write a short, conversational comment in ${commenter.language === 'es' ? 'Spanish' : 'English'} 
            (max 2 sentences) responding to this social media post: "${postDetails.content}"`;
          
          commentContent = await generateOpenRouterResponse(prompt);
        } else {
          // Generate a simple random comment
          const comments = [
            "¡Me encanta esta idea!",
            "Great point!",
            "No estoy seguro si estoy de acuerdo.",
            "This is exactly what I needed to hear.",
            "¿Alguien ha probado esto antes?",
            "I've been thinking about this too.",
            "Excelente publicación, muy útil.",
            "Thanks for sharing your experience!",
            "¿Puedes dar más detalles?",
            "Let me know if you need any help."
          ];
          commentContent = comments[Math.floor(Math.random() * comments.length)];
        }
        
        // Save the comment
        const newComment: any = {
          postId,
          userId: commenterId,
          content: commentContent,
          likes: Math.floor(Math.random() * 10),
          isReply: false,
          parentId: null
        };
        
        const [comment] = await db.insert(comments).values(newComment).returning({ id: comments.id });
        commentIds.push(comment.id);
        
        // 50% chance of the post author replying to this comment
        if (Math.random() > 0.5) {
          let replyContent;
          
          if (postAuthor.isBot) {
            // AI-generated response
            const userInterests = postAuthor.interests || ['music'];
            const prompt = `You are a social media user with the following personality: ${postAuthor.personality || 'friendly and engaged'}. 
              You're interested in: ${userInterests.join(', ')}.
              You made a post saying: "${postDetails.content}"
              Someone commented: "${commentContent}"
              Please write a brief reply in ${postAuthor.language === 'es' ? 'Spanish' : 'English'} (1-2 sentences) to this comment.`;
            
            replyContent = await generateOpenRouterResponse(prompt);
          } else {
            // Generate a simple random reply
            const replies = [
              "¡Gracias por tu comentario!",
              "Thanks for the feedback!",
              "Estoy totalmente de acuerdo contigo.",
              "I appreciate your perspective.",
              "Buena observación, no lo había pensado así.",
              "Great point, I'll keep that in mind.",
              "Me alegra que te guste.",
              "Let's discuss this more via DM.",
              "¿Tienes alguna otra sugerencia?",
              "I'll be sharing more about this soon."
            ];
            replyContent = replies[Math.floor(Math.random() * replies.length)];
          }
          
          const newReply: any = {
            postId,
            userId: postDetails.userId,
            content: replyContent,
            likes: Math.floor(Math.random() * 5),
            isReply: true,
            parentId: comment.id
          };
          
          await db.insert(comments).values(newReply);
        }
      }
    }
    
    console.log("✅ Social network seed completed successfully!");
  } catch (error) {
    console.error("Error seeding social network:", error);
  }
}

seedSocialNetwork().catch(console.error);